[package]
name = "server_udp"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
clap = { version = "4.5.32", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
